### ISSUE TITLE
Error in DB

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_ResourceManagement#118]
![image](https://user-images.githubusercontent.com/15946467/102130880-b2ebc100-3e51-11eb-8b80-0f1015439684.png)

**Comment by geofranzi** [comment]
1. Create booking
2. Add resource (do not fill date)
3. Save (it seems date is not checked)

![image](https://user-images.githubusercontent.com/15946467/104422508-2847d000-557d-11eb-92c6-7798d17dbcda.png)
![image](https://user-images.githubusercontent.com/15946467/104422529-2d0c8400-557d-11eb-9327-ec37dba50ec8.png)

**Comment by EleonoraPetzold** [comment]
- [ ] set default date if you add a resource to event
- [ ]  check date before save

**Comment by EleonoraPetzold** [comment]
Save without date not possible.

**Comment by bayramliaziz** [comment]
- Add a resource or more and click continue booking
- Click Add more Resources
- Add a resource or more and click continue booking ( calendar fields for newly added resources fields are empty)
- Fill in the required fields except for the empty calendar fields
- Click Save 

Result: 
- Start and End dates for resources with empty calendar fields are 01.01.0001

**Comment by EleonoraPetzold** [comment]
Thanks for testing again.
For me, it is not reproducible. After adding a resource start and end are filled.
![image](https://user-images.githubusercontent.com/42029171/105954810-885a6e00-6075-11eb-9fa5-1f47eadeb4e4.png)

01.01.0001 is the default value when we catch the case the field are empty. Because date is not nullable. 

@geofranzi, can you try that too?
